# Generated by Django 5.2.8 on 2025-11-11 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='activate',
            new_name='active',
        ),
    ]
