# Generated by Django 5.2.8 on 2025-11-26 10:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_tag_alter_course_image_alter_lesson_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=cloudinary.models.CloudinaryField(
                default="https://res.cloudinary.com/dt1pa28g2/image/upload/v1764153082/sbcf-default-avatar_tgyi8q.webp",
                max_length=255,
            ),
        ),
    ]
